import 'ai_chat_types.dart';

class AiToolRegistry {
  AiToolRegistry._();

  static final List<AiToolDefinition> _definitions = <AiToolDefinition>[
    _def(
      name: 'app.help',
      aliases: const <String>[],
      description: 'شرح كيفية استخدام التطبيق أو جزء منه دون تعديل البيانات.',
      category: 'system',
      operationType: AiToolOperationType.system,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['app.help'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'question': _nullableString('سؤال المستخدم عن كيفية الاستخدام.'),
        'module': _nullableEnum(
          <String>['properties', 'tenants', 'contracts', 'reports', 'maintenance'],
          'الوحدة المطلوبة إن كانت معروفة.',
        ),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'لا ينفذ أي تعديل أو حذف.',
        'يجيب بالاعتماد على سياق التطبيق والقواعد الداخلية فقط.',
      ],
      handlerName: 'app.help',
      readBackTool: null,
      examplesAr: const <String>[
        'كيف أضيف مستأجر؟',
        'اشرح لي طريقة إصدار عقد.',
      ],
      disambiguationStrategy: 'إن كانت الوحدة غير واضحة فاسأل المستخدم هل يقصد العقارات أو العقود أو التقارير.',
      validationStrategy: 'سؤال حر آمن بلا تغيير بيانات.',
    ),
    _def(
      name: 'app.module_help',
      aliases: const <String>[],
      description: 'شرح مختصر لوحدة محددة داخل التطبيق.',
      category: 'system',
      operationType: AiToolOperationType.system,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['app.help'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'module': _nullableEnum(
          <String>['properties', 'tenants', 'contracts', 'reports', 'maintenance'],
          'اسم الوحدة.',
        ),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا ينفذ أي عمليات كتابة.'],
      handlerName: 'app.module_help',
      readBackTool: null,
      examplesAr: const <String>['اشرح وحدة العقود', 'كيف تعمل وحدة التقارير؟'],
      disambiguationStrategy: 'إذا لم يحدد الوحدة بوضوح فاطلب منه تحديدها.',
      validationStrategy: 'يتحقق من أن اسم الوحدة ضمن الوحدات المدعومة.',
    ),
    _def(
      name: 'app.capabilities',
      aliases: const <String>[],
      description: 'عرض ما يستطيع المساعد فعله داخل هذا الحساب.',
      category: 'system',
      operationType: AiToolOperationType.system,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['app.help'],
      inputSchema: _schema(const <String, Map<String, dynamic>>{}),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يعرض الصلاحيات والقدرات العامة فقط.'],
      handlerName: 'app.capabilities',
      readBackTool: null,
      examplesAr: const <String>['ماذا يمكنك أن تفعل؟'],
      disambiguationStrategy: 'لا ينطبق.',
      validationStrategy: 'لا يحتاج حقولاً.',
    ),
    _def(
      name: 'app.explain_workflow',
      aliases: const <String>[],
      description: 'شرح سير عمل مثل إضافة عقد أو تسجيل دفعة أو فتح شاشة.',
      category: 'system',
      operationType: AiToolOperationType.system,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['app.help'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'workflow': _nullableString('اسم أو وصف سير العمل المطلوب شرحه.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا يغير البيانات.'],
      handlerName: 'app.explain_workflow',
      readBackTool: null,
      examplesAr: const <String>['اشرح لي سير إضافة عقد', 'كيف يتم تسجيل دفعة؟'],
      disambiguationStrategy: 'إذا كان سير العمل عامًا فاسأل هل المقصود عقد أو دفعة أو صيانة.',
      validationStrategy: 'وصف سير عمل نصي.',
    ),
    _def(
      name: 'properties.search',
      aliases: const <String>['get_properties_list', 'get_properties_summary', 'get_building_units'],
      description: 'البحث عن العقارات والوحدات وعرض النتائج المطابقة.',
      category: 'properties',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['properties.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('الاسم أو جزء منه أو رقم الوحدة.'),
        'property_type': _nullableEnum(
          <String>['apartment', 'villa', 'building', 'land', 'office', 'shop', 'warehouse'],
          'نوع العقار إن وجد.',
        ),
        'include_archived': _nullableBoolean('هل يتم تضمين المؤرشف.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يحترم نطاق الحساب الحالي.', 'لا يعرض بيانات خارج نطاق المكتب أو العميل الحالي.'],
      handlerName: 'properties.search',
      readBackTool: null,
      examplesAr: const <String>['ابحث عن برج النخيل', 'أرني الوحدات الشاغرة في عمارة السلام'],
      disambiguationStrategy: 'إذا تطابق أكثر من عقار أو وحدة تُعرض قائمة مرشحين.',
      validationStrategy: 'يقبل الاستعلام النصي فقط لأدوات البحث.',
    ),
    _def(
      name: 'properties.get',
      aliases: const <String>['get_property_details', 'get_property_service_details', 'get_property_services'],
      description: 'عرض تفاصيل عقار محدد وخدماته وإعداداته.',
      category: 'properties',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['properties.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'property_id': _nullableString('معرف العقار إن كان معروفًا.'),
        'query': _nullableString('اسم العقار أو الوحدة.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['إذا لم يحدد العقار بدقة فيجب طلب الاختيار من المرشحين.'],
      handlerName: 'properties.get',
      readBackTool: null,
      examplesAr: const <String>['اعرض تفاصيل عقار برج النخيل'],
      disambiguationStrategy: 'اختيار من قائمة العقارات المطابقة.',
      validationStrategy: 'إما property_id أو query.',
    ),
    _def(
      name: 'properties.create',
      aliases: const <String>['add_property'],
      description: 'تهيئة أو إنشاء عقار جديد بعد التحقق من الحقول الإلزامية.',
      category: 'properties',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['properties.create'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'name': _nullableString('اسم العقار.'),
        'type': _nullableEnum(
          <String>['apartment', 'villa', 'building', 'land', 'office', 'shop', 'warehouse'],
          'نوع العقار.',
        ),
        'address': _nullableString('العنوان.'),
        'rentalMode': _nullableEnum(<String>['wholeBuilding', 'perUnit'], 'نمط التأجير.'),
        'totalUnits': _nullableNumber('عدد الوحدات.'),
        'notes': _nullableString('ملاحظات إضافية.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'المستخدم يحتاج صلاحية إنشاء عقار.',
        'الاسم ونوع العقار مطلوبان.',
        'إذا كان العقار عمارة بنظام وحدات فيجب التحقق من عدد الوحدات أو فتح الشاشة.',
      ],
      handlerName: 'properties.create',
      readBackTool: 'properties.get',
      examplesAr: const <String>['أضف عقارًا باسم برج الياسمين'],
      disambiguationStrategy: 'عند تعارض الاسم اطلب من المستخدم التأكيد أو التمييز.',
      validationStrategy: 'التحقق من الحقول والحدود والقيم المقبولة قبل التنفيذ.',
    ),
    _def(
      name: 'properties.update',
      aliases: const <String>['edit_property'],
      description: 'تعديل بيانات عقار موجود بعد التأكيد.',
      category: 'properties',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['properties.update'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('اسم أو مرجع العقار المراد تعديله.'),
        'name': _nullableString('الاسم الجديد إن وجد.'),
        'address': _nullableString('العنوان الجديد.'),
        'notes': _nullableString('الوصف أو الملاحظات.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يجب تحديد العقار المراد تعديله بدقة قبل التنفيذ.'],
      handlerName: 'properties.update',
      readBackTool: 'properties.get',
      examplesAr: const <String>['عدل عنوان برج النخيل'],
      disambiguationStrategy: 'إذا تعددت النتائج اطلب الاختيار.',
      validationStrategy: 'لا تنفذ بدون حقل تعديل فعلي.',
    ),
    _def(
      name: 'units.search',
      aliases: const <String>[],
      description: 'البحث عن الوحدات داخل العمائر.',
      category: 'units',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['units.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('اسم أو رقم الوحدة.'),
        'building_query': _nullableString('اسم العمارة إن وجد.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['البحث داخل نطاق الحساب فقط.'],
      handlerName: 'units.search',
      readBackTool: null,
      examplesAr: const <String>['ابحث عن الشقة 12'],
      disambiguationStrategy: 'إذا تكرر رقم الوحدة اطلب تحديد العقار.',
      validationStrategy: 'استعلام نصي آمن.',
    ),
    _def(
      name: 'units.available',
      aliases: const <String>[],
      description: 'عرض الوحدات الشاغرة أو المتاحة.',
      category: 'units',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['units.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'building_query': _nullableString('اسم العمارة إن وجد.'),
        'property_query': _nullableString('اسم العقار الأعلى إن وجد.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['تعتمد الإتاحة على العقود الحالية غير المنتهية.'],
      handlerName: 'units.available',
      readBackTool: null,
      examplesAr: const <String>['ما الوحدات الشاغرة اليوم؟'],
      disambiguationStrategy: 'إذا كان العقار غير محدد وكان هناك تكرار فاطلب التحديد.',
      validationStrategy: 'فلترة قراءة فقط.',
    ),
    _def(
      name: 'tenants.search',
      aliases: const <String>['get_tenants_list'],
      description: 'البحث عن المستأجرين والعملاء ومقدمي الخدمة.',
      category: 'tenants',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['tenants.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('الاسم أو الهوية أو الجوال.'),
        'clientType': _nullableString('نوع العميل إن وجد.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['إذا تطابق أكثر من أحمد مثلًا تعرض قائمة مرشحين.'],
      handlerName: 'tenants.search',
      readBackTool: null,
      examplesAr: const <String>['ابحث عن أحمد', 'أرني مقدمي الخدمة'],
      disambiguationStrategy: 'عرض مرشحين مع الهاتف أو نوع العميل.',
      validationStrategy: 'استعلام نصي فقط.',
    ),
    _def(
      name: 'tenants.get',
      aliases: const <String>['get_tenant_details'],
      description: 'عرض تفاصيل عميل أو مستأجر محدد.',
      category: 'tenants',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['tenants.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'tenant_id': _nullableString('معرف العميل إن كان معروفًا.'),
        'query': _nullableString('الاسم أو الهوية أو الجوال.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا تعرض تفاصيل عميل غير محدد بشكل صحيح.'],
      handlerName: 'tenants.get',
      readBackTool: null,
      examplesAr: const <String>['اعرض تفاصيل أحمد علي'],
      disambiguationStrategy: 'إذا تعددت النتائج اطلب الاختيار.',
      validationStrategy: 'إما tenant_id أو query.',
    ),
    _def(
      name: 'tenants.create',
      aliases: const <String>['add_tenant', 'add_client_record'],
      description: 'تهيئة أو إنشاء مستأجر أو عميل جديد بعد التأكيد.',
      category: 'tenants',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['tenants.create'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'clientType': _nullableString('tenant أو company أو serviceProvider.'),
        'fullName': _nullableString('الاسم الكامل.'),
        'phone': _nullableString('رقم الجوال.'),
        'nationalId': _nullableString('رقم الهوية إن وجد.'),
        'email': _nullableString('البريد الإلكتروني.'),
        'notes': _nullableString('ملاحظات.'),
        'attachmentPaths': _nullableArrayOfStrings('المرفقات إن وجدت.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'الاسم الكامل ونوع العميل غالبًا مطلوبان.',
        'المستخدم يحتاج صلاحية إنشاء عملاء.',
      ],
      handlerName: 'tenants.create',
      readBackTool: 'tenants.get',
      examplesAr: const <String>['أضف مستأجرًا باسم أحمد علي'],
      disambiguationStrategy: 'عند وجود تطابق قوي مع عميل قائم اطلب التأكيد.',
      validationStrategy: 'التحقق من الحقول المطلوبة وصيغة الهاتف والبريد.',
    ),
    _def(
      name: 'tenants.update',
      aliases: const <String>['edit_tenant'],
      description: 'تعديل بيانات عميل أو مستأجر موجود.',
      category: 'tenants',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['tenants.update'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('اسم أو هوية العميل.'),
        'phone': _nullableString('الجوال الجديد.'),
        'email': _nullableString('البريد الجديد.'),
        'notes': _nullableString('ملاحظات جديدة.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يجب تحديد العميل بدقة ووجود تعديل فعلي.'],
      handlerName: 'tenants.update',
      readBackTool: 'tenants.get',
      examplesAr: const <String>['حدّث رقم أحمد علي'],
      disambiguationStrategy: 'إذا تعددت النتائج اطلب الاختيار.',
      validationStrategy: 'لا تنفذ بلا تغيير فعلي.',
    ),
    _def(
      name: 'contracts.search',
      aliases: const <String>['get_contracts_list', 'get_active_contracts'],
      description: 'البحث عن العقود وعرض حالتها.',
      category: 'contracts',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['contracts.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('رقم العقد أو اسم المستأجر أو العقار.'),
        'status': _nullableString('active أو expired أو terminated.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يعرض العقود في نطاق الحساب فقط.'],
      handlerName: 'contracts.search',
      readBackTool: null,
      examplesAr: const <String>['ابحث عن عقد أحمد', 'أرني العقود النشطة'],
      disambiguationStrategy: 'إذا كان الاسم عامًا اطلب الاختيار من قائمة العقود.',
      validationStrategy: 'فلترة قراءة فقط.',
    ),
    _def(
      name: 'contracts.get',
      aliases: const <String>['get_contract_details', 'get_contract_invoice_history'],
      description: 'عرض تفاصيل عقد ودفعاته المرتبطة.',
      category: 'contracts',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['contracts.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'contract_id': _nullableString('معرف العقد إن وجد.'),
        'query': _nullableString('رقم العقد أو اسم المستأجر أو العقار.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا تعرض دفعات عقد غير محدد بدقة.'],
      handlerName: 'contracts.get',
      readBackTool: null,
      examplesAr: const <String>['اعرض تفاصيل العقد 2025-3'],
      disambiguationStrategy: 'عرض قائمة مرشحين إن لزم.',
      validationStrategy: 'إما contract_id أو query.',
    ),
    _def(
      name: 'contracts.create',
      aliases: const <String>['create_contract'],
      description: 'تهيئة أو إنشاء عقد إيجار بعد التحقق من التوفر والتواريخ والمبالغ والصلاحيات.',
      category: 'contracts',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.critical,
      requiresConfirmation: true,
      requiredPermissions: const <String>['contracts.create'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'property_id': _nullableString('معرف العقار إن كان معروفًا.'),
        'property_query': _nullableString('اسم العقار أو الوحدة.'),
        'tenant_id': _nullableString('معرف المستأجر إن كان معروفًا.'),
        'tenant_query': _nullableString('اسم المستأجر أو العميل.'),
        'startDate': _nullableString('تاريخ البداية YYYY-MM-DD.'),
        'endDate': _nullableString('تاريخ النهاية YYYY-MM-DD.'),
        'rentAmount': _nullableNumber('قيمة الإيجار أو القسط.'),
        'paymentCycle': _nullableEnum(
          <String>['monthly', 'quarterly', 'semiAnnual', 'annual'],
          'دورة السداد.',
        ),
        'notes': _nullableString('ملاحظات العقد.'),
        'attachmentPaths': _nullableArrayOfStrings('مرفقات العقد.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'المستخدم يحتاج صلاحية إنشاء عقد.',
        'يجب وجود مستأجر وعقار داخل نطاق الحساب.',
        'لا يسمح بتداخل عقد نشط على نفس الوحدة.',
        'يجب أن تكون التواريخ والمبلغ صالحة.',
      ],
      handlerName: 'contracts.create',
      readBackTool: 'contracts.get',
      examplesAr: const <String>['أنشئ عقدًا لأحمد في الشقة 12 من 2026-05-01 إلى 2027-04-30'],
      disambiguationStrategy: 'إذا تطابق اسم المستأجر أو الوحدة مع أكثر من سجل فاطلب الاختيار.',
      validationStrategy: 'التحقق من الحقول والتوافر وعدم التداخل قبل التنفيذ.',
    ),
    _def(
      name: 'contracts.update',
      aliases: const <String>['edit_contract', 'renew_contract'],
      description: 'تعديل أو تجديد عقد قائم بعد التأكيد.',
      category: 'contracts',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.critical,
      requiresConfirmation: true,
      requiredPermissions: const <String>['contracts.update'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('رقم العقد أو مرجعه.'),
        'endDate': _nullableString('تاريخ النهاية الجديد إن وجد.'),
        'rentAmount': _nullableNumber('القيمة الجديدة.'),
        'notes': _nullableString('ملاحظات التعديل.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا يجوز تعديل عقد غير محدد بدقة.', 'لا يجوز تعديل عقد منهي بطريقة غير مسموحة.'],
      handlerName: 'contracts.update',
      readBackTool: 'contracts.get',
      examplesAr: const <String>['مدد العقد 2025-1'],
      disambiguationStrategy: 'إذا تعددت العقود المحتملة اطلب الاختيار.',
      validationStrategy: 'التحقق من وجود حقل تعديل فعلي.',
    ),
    _def(
      name: 'contracts.terminate',
      aliases: const <String>['terminate_contract'],
      description: 'إنهاء عقد إيجار قائم بعد تأكيد قوي.',
      category: 'contracts',
      operationType: AiToolOperationType.deleteAction,
      riskLevel: AiToolRiskLevel.critical,
      requiresConfirmation: true,
      requiredPermissions: const <String>['contracts.terminate'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('رقم العقد أو مرجعه.'),
        'reason': _nullableString('سبب الإنهاء.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يلزم تأكيد قوي من المستخدم.', 'لا ينفذ على عقد منهي أصلًا.'],
      handlerName: 'contracts.terminate',
      readBackTool: 'contracts.get',
      examplesAr: const <String>['أنهِ العقد 2025-3'],
      disambiguationStrategy: 'إذا كان المرجع غير كافٍ اطلب التحديد.',
      validationStrategy: 'تأكيد صريح وتنفيذ من المعطيات المخزنة فقط.',
    ),
    _def(
      name: 'contracts.expiring',
      aliases: const <String>[],
      description: 'عرض العقود القريبة من الانتهاء.',
      category: 'contracts',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['contracts.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'days': _nullableNumber('عدد الأيام القادمة.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يحسب من التواريخ الفعلية للعقود داخل النظام.'],
      handlerName: 'contracts.expiring',
      readBackTool: null,
      examplesAr: const <String>['أرني العقود التي ستنتهي خلال 30 يومًا'],
      disambiguationStrategy: 'لا ينطبق.',
      validationStrategy: 'فلتر عددي بسيط.',
    ),
    _def(
      name: 'invoices.search',
      aliases: const <String>['get_invoices_list', 'get_unpaid_invoices', 'get_invoices_by_type'],
      description: 'البحث عن الفواتير والسندات والمتأخرات.',
      category: 'invoices',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['invoices.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('رقم الفاتورة أو العقد أو اسم المستأجر.'),
        'status': _nullableString('paid أو unpaid أو overdue.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['النتائج يجب أن تأتي من سجلات الفواتير الفعلية فقط.'],
      handlerName: 'invoices.search',
      readBackTool: null,
      examplesAr: const <String>['اعرض الفواتير المتأخرة'],
      disambiguationStrategy: 'إذا كان المرجع عامًا اطلب التحديد.',
      validationStrategy: 'قراءة فقط.',
    ),
    _def(
      name: 'invoices.get',
      aliases: const <String>['get_invoice_payment_history'],
      description: 'عرض فاتورة محددة وسجل السداد المرتبط بها.',
      category: 'invoices',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['invoices.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'invoiceSerialNo': _nullableString('الرقم التسلسلي للفاتورة.'),
        'invoice_id': _nullableString('معرف الفاتورة إن وجد.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا تعرض فاتورة غير محددة بدقة.'],
      handlerName: 'invoices.get',
      readBackTool: null,
      examplesAr: const <String>['اعرض الفاتورة 2025-44'],
      disambiguationStrategy: 'إذا كان المرجع غير كافٍ اطلب الرقم أو الاختيار.',
      validationStrategy: 'إما invoiceSerialNo أو invoice_id.',
    ),
    _def(
      name: 'invoices.create',
      aliases: const <String>['create_invoice'],
      description: 'إنشاء فاتورة لعقد محدد بعد التأكيد.',
      category: 'invoices',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['invoices.create'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'contract_id': _nullableString('معرف العقد إن كان معروفًا.'),
        'query': _nullableString('مرجع العقد أو اسم المستأجر.'),
        'amount': _nullableNumber('المبلغ.'),
        'dueDate': _nullableString('تاريخ الاستحقاق.'),
        'notes': _nullableString('وصف الفاتورة.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يجب ربط الفاتورة بعقد صالح داخل النطاق الحالي.'],
      handlerName: 'invoices.create',
      readBackTool: 'invoices.get',
      examplesAr: const <String>['أنشئ فاتورة بقيمة 3000 على عقد أحمد'],
      disambiguationStrategy: 'إذا تعددت العقود اطلب الاختيار.',
      validationStrategy: 'التحقق من المبلغ وتاريخ الاستحقاق والعقد.',
    ),
    _def(
      name: 'payments.search',
      aliases: const <String>[],
      description: 'قراءة عمليات السداد المتاحة في التطبيق.',
      category: 'payments',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['payments.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('مرجع العقد أو الفاتورة أو المستأجر.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['إذا لم تكن هناك سجلات سداد مستقلة، يعاد توضيح أن القراءة تتم من الفواتير المرتبطة فقط.'],
      handlerName: 'payments.search',
      readBackTool: null,
      examplesAr: const <String>['أرني سداد أحمد'],
      disambiguationStrategy: 'يعتمد على العقود أو الفواتير المطابقة.',
      validationStrategy: 'قراءة فقط.',
    ),
    _def(
      name: 'payments.get',
      aliases: const <String>[],
      description: 'عرض عملية سداد محددة إن كانت مدعومة.',
      category: 'payments',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['payments.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'payment_id': _nullableString('معرف عملية السداد إن وجد.'),
        'invoice_id': _nullableString('معرف الفاتورة المرتبطة إن وجد.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['إذا لم يدعم التطبيق سجل سداد مستقل يعاد رد غير مدعوم بوضوح.'],
      handlerName: 'payments.get',
      readBackTool: null,
      examplesAr: const <String>['اعرض دفعة الفاتورة الحالية'],
      disambiguationStrategy: 'لا ينطبق.',
      validationStrategy: 'يحتاج معرفًا دقيقًا.',
      supported: false,
    ),
    _def(
      name: 'payments.create',
      aliases: const <String>['record_payment'],
      description: 'تسجيل دفعة على فاتورة أو عقد بعد التأكيد.',
      category: 'payments',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.critical,
      requiresConfirmation: true,
      requiredPermissions: const <String>['payments.create'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'invoice_id': _nullableString('معرف الفاتورة إن كان معروفًا.'),
        'invoiceSerialNo': _nullableString('رقم الفاتورة.'),
        'query': _nullableString('مرجع الفاتورة أو العقد أو المستأجر.'),
        'amount': _nullableNumber('المبلغ المدفوع.'),
        'paymentMethod': _nullableString('طريقة الدفع.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'المستخدم يحتاج صلاحية تسجيل دفعة.',
        'يجب أن تكون الفاتورة موجودة وغير ملغاة والمبلغ أكبر من صفر.',
      ],
      handlerName: 'payments.create',
      readBackTool: 'invoices.get',
      examplesAr: const <String>['سجل دفعة 3000 على فاتورة أحمد'],
      disambiguationStrategy: 'إذا تعددت الفواتير اطلب الاختيار.',
      validationStrategy: 'التحقق من الفاتورة والمبلغ وطريقة الدفع قبل التنفيذ.',
    ),
    _def(
      name: 'maintenance.search',
      aliases: const <String>['get_maintenance_list'],
      description: 'البحث عن طلبات الصيانة.',
      category: 'maintenance',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['maintenance.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('العنوان أو الرقم أو العقار.'),
        'status': _nullableString('الحالة.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['قراءة فقط ضمن النطاق.'],
      handlerName: 'maintenance.search',
      readBackTool: null,
      examplesAr: const <String>['اعرض طلبات الصيانة المفتوحة'],
      disambiguationStrategy: 'إذا كان المرجع غير كافٍ اطلب الاختيار.',
      validationStrategy: 'بحث وفلترة فقط.',
    ),
    _def(
      name: 'maintenance.get',
      aliases: const <String>['get_maintenance_details'],
      description: 'عرض تفاصيل طلب صيانة محدد.',
      category: 'maintenance',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['maintenance.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'request_id': _nullableString('معرف الطلب إن وجد.'),
        'query': _nullableString('العنوان أو الرقم أو العقار.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا تعرض طلبًا غير محدد بدقة.'],
      handlerName: 'maintenance.get',
      readBackTool: null,
      examplesAr: const <String>['اعرض تفاصيل الطلب M-12'],
      disambiguationStrategy: 'إذا تعددت الطلبات اطلب الاختيار.',
      validationStrategy: 'إما request_id أو query.',
    ),
    _def(
      name: 'maintenance.create_ticket',
      aliases: const <String>['create_maintenance_request'],
      description: 'إنشاء طلب صيانة بعد التحقق والتأكيد.',
      category: 'maintenance',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['maintenance.create'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'property_id': _nullableString('معرف العقار.'),
        'property_query': _nullableString('اسم العقار أو الوحدة.'),
        'title': _nullableString('العنوان.'),
        'description': _nullableString('الوصف.'),
        'priority': _nullableEnum(<String>['low', 'medium', 'high', 'urgent'], 'الأولوية.'),
        'provider': _nullableString('مقدم الخدمة إن وجد.'),
        'attachmentPaths': _nullableArrayOfStrings('المرفقات.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'يحتاج المستخدم صلاحية إنشاء طلب صيانة.',
        'يجب تحديد العقار والوصف والعنوان أو نوع الخدمة.',
      ],
      handlerName: 'maintenance.create_ticket',
      readBackTool: 'maintenance.get',
      examplesAr: const <String>['أنشئ طلب صيانة لمكيف الشقة 12'],
      disambiguationStrategy: 'إذا كان العقار أو مقدم الخدمة غامضًا اطلب الاختيار.',
      validationStrategy: 'التحقق من الحقول الإلزامية ثم طلب التأكيد.',
    ),
    _def(
      name: 'maintenance.update_status',
      aliases: const <String>['update_maintenance_status'],
      description: 'تحديث حالة طلب صيانة بعد التأكيد.',
      category: 'maintenance',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['maintenance.update'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'query': _nullableString('مرجع الطلب.'),
        'status': _nullableString('الحالة الجديدة.'),
        'notes': _nullableString('ملاحظات التحديث.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يجب تحديد الطلب والحالة الجديدة بدقة.'],
      handlerName: 'maintenance.update_status',
      readBackTool: 'maintenance.get',
      examplesAr: const <String>['حوّل طلب الصيانة إلى مكتمل'],
      disambiguationStrategy: 'إذا تعددت الطلبات اطلب الاختيار.',
      validationStrategy: 'التحقق من الحالة الجديدة قبل التنفيذ.',
    ),
    _def(
      name: 'reports.arrears_summary',
      aliases: const <String>[],
      description: 'تقرير المتأخرات للفترة المطلوبة.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.medium,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view', 'reports.financial'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'from_date': _nullableString('بداية الفترة YYYY-MM-DD.'),
        'to_date': _nullableString('نهاية الفترة YYYY-MM-DD.'),
        'property_query': _nullableString('العقار إن وجد.'),
      }),
      resultSchema: _reportSchema('arrears_summary'),
      businessRules: const <String>['يحسب من الفواتير والعقود الفعلية، وليس من توقعات لغوية.'],
      handlerName: 'reports.arrears_summary',
      readBackTool: null,
      examplesAr: const <String>['طلع لي تقرير المتأخرات لهذا الشهر'],
      disambiguationStrategy: 'إذا كان العقار غامضًا اطلب الاختيار.',
      validationStrategy: 'فلاتر التقرير تخضع للتحقق قبل الحساب.',
    ),
    _def(
      name: 'reports.owner_statement',
      aliases: const <String>['get_owner_report_details'],
      description: 'كشف مالك محسوب من بيانات النظام.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.medium,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view', 'reports.financial'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'owner_query': _nullableString('اسم أو مرجع المالك.'),
        'from_date': _nullableString('بداية الفترة.'),
        'to_date': _nullableString('نهاية الفترة.'),
      }),
      resultSchema: _reportSchema('owner_statement'),
      businessRules: const <String>['يعتمد على خدمات التقرير الداخلية فقط.'],
      handlerName: 'reports.owner_statement',
      readBackTool: null,
      examplesAr: const <String>['أعطني كشف المالك لهذا الشهر'],
      disambiguationStrategy: 'إذا لم يوجد مالك مطابق يعاد غير مدعوم أو يطلب التحديد.',
      validationStrategy: 'فلترة تقرير.',
      supported: false,
    ),
    _def(
      name: 'reports.tenant_statement',
      aliases: const <String>[],
      description: 'كشف مستأجر عن الفواتير والسداد.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.medium,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view', 'reports.financial'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'tenant_query': _nullableString('اسم أو مرجع المستأجر.'),
        'from_date': _nullableString('بداية الفترة.'),
        'to_date': _nullableString('نهاية الفترة.'),
      }),
      resultSchema: _reportSchema('tenant_statement'),
      businessRules: const <String>['يحصل من الفواتير والعقود الفعلية للمستأجر.'],
      handlerName: 'reports.tenant_statement',
      readBackTool: null,
      examplesAr: const <String>['أعطني كشف أحمد'],
      disambiguationStrategy: 'إذا تعدد الاسم اطلب الاختيار.',
      validationStrategy: 'فلترة تقرير.',
    ),
    _def(
      name: 'reports.occupancy_rate',
      aliases: const <String>['get_properties_report'],
      description: 'تقرير نسبة الإشغال.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'property_query': _nullableString('اسم العقار إن وجد.'),
      }),
      resultSchema: _reportSchema('occupancy_rate'),
      businessRules: const <String>['يحسب من العقارات والعقود الحالية.'],
      handlerName: 'reports.occupancy_rate',
      readBackTool: null,
      examplesAr: const <String>['ما نسبة الإشغال الحالية؟'],
      disambiguationStrategy: 'إذا كان العقار غامضًا اطلب التحديد.',
      validationStrategy: 'قراءة تقرير فقط.',
    ),
    _def(
      name: 'reports.rent_collection',
      aliases: const <String>['get_financial_summary', 'get_office_report'],
      description: 'تقرير تحصيل الإيجارات.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.medium,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view', 'reports.financial'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'from_date': _nullableString('بداية الفترة.'),
        'to_date': _nullableString('نهاية الفترة.'),
        'property_query': _nullableString('العقار إن وجد.'),
      }),
      resultSchema: _reportSchema('rent_collection'),
      businessRules: const <String>['يحسب من الفواتير والسداد الفعلي.'],
      handlerName: 'reports.rent_collection',
      readBackTool: null,
      examplesAr: const <String>['أرني تحصيل الإيجارات هذا الشهر'],
      disambiguationStrategy: 'إذا كان العقار غامضًا اطلب التحديد.',
      validationStrategy: 'فلاتر تقرير.',
    ),
    _def(
      name: 'reports.income_expense',
      aliases: const <String>['get_financial_summary'],
      description: 'تقرير الإيرادات والمصروفات.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.medium,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view', 'reports.financial'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'from_date': _nullableString('بداية الفترة.'),
        'to_date': _nullableString('نهاية الفترة.'),
        'property_query': _nullableString('العقار إن وجد.'),
      }),
      resultSchema: _reportSchema('income_expense'),
      businessRules: const <String>['تجمع الإيرادات والمصروفات من السجلات الفعلية فقط.'],
      handlerName: 'reports.income_expense',
      readBackTool: null,
      examplesAr: const <String>['أعطني تقرير الإيرادات والمصروفات'],
      disambiguationStrategy: 'إذا كان العقار غامضًا اطلب التحديد.',
      validationStrategy: 'فلاتر تقرير.',
    ),
    _def(
      name: 'reports.contracts_expiring',
      aliases: const <String>[],
      description: 'تقرير العقود القريبة من الانتهاء.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'days': _nullableNumber('عدد الأيام القادمة.'),
      }),
      resultSchema: _reportSchema('contracts_expiring'),
      businessRules: const <String>['يعتمد على تواريخ انتهاء العقود الفعلية.'],
      handlerName: 'reports.contracts_expiring',
      readBackTool: null,
      examplesAr: const <String>['أرني العقود التي ستنتهي قريبًا'],
      disambiguationStrategy: 'لا ينطبق.',
      validationStrategy: 'فلتر عددي.',
    ),
    _def(
      name: 'reports.vacant_units',
      aliases: const <String>[],
      description: 'تقرير الوحدات الشاغرة.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'building_query': _nullableString('العقار أو العمارة إن وجدت.'),
      }),
      resultSchema: _reportSchema('vacant_units'),
      businessRules: const <String>['يبنى من العقارات والعقود الحالية.'],
      handlerName: 'reports.vacant_units',
      readBackTool: null,
      examplesAr: const <String>['أرني الوحدات الشاغرة'],
      disambiguationStrategy: 'إذا لزم اطلب تحديد العقار.',
      validationStrategy: 'فلترة تقرير.',
    ),
    _def(
      name: 'reports.maintenance_summary',
      aliases: const <String>['get_services_report', 'get_maintenance_list'],
      description: 'تقرير ملخص الصيانة.',
      category: 'reports',
      operationType: AiToolOperationType.report,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['reports.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'from_date': _nullableString('بداية الفترة.'),
        'to_date': _nullableString('نهاية الفترة.'),
        'status': _nullableString('حالة الطلب.'),
      }),
      resultSchema: _reportSchema('maintenance_summary'),
      businessRules: const <String>['يعتمد على طلبات الصيانة وسجلاتها الفعلية.'],
      handlerName: 'reports.maintenance_summary',
      readBackTool: null,
      examplesAr: const <String>['أعطني ملخص الصيانة لهذا الشهر'],
      disambiguationStrategy: 'لا ينطبق.',
      validationStrategy: 'فلترة تقرير.',
    ),
    _def(
      name: 'periodic_services.search',
      aliases: const <String>['get_property_services', 'get_property_service_details', 'get_periodic_service_history'],
      description: 'قراءة إعدادات وسجل الخدمات الدورية لعقار محدد مثل النظافة والمصعد والإنترنت والمياه والكهرباء.',
      category: 'periodic_services',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['maintenance.view'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'property_query': _nullableString('اسم العقار أو الوحدة.'),
        'serviceType': _nullableEnum(
          <String>['cleaning', 'elevator', 'internet', 'water', 'electricity'],
          'نوع الخدمة إن كان المطلوب خدمة محددة.',
        ),
        'includeHistory': _nullableBoolean('هل يتم إرجاع سجل الخدمة المحددة إن وجد.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'قراءة فقط من إعدادات الخدمات وطلبات الصيانة الفعلية.',
        'إذا كان العقار غير محدد بدقة فاطلب التحديد.',
      ],
      handlerName: 'periodic_services.search',
      readBackTool: null,
      examplesAr: const <String>['اعرض خدمات عقار برج النخيل', 'ما سجل خدمة المياه في الشقة 12؟'],
      disambiguationStrategy: 'إذا تعدد العقار أو الوحدة اطلب اختيار السجل الصحيح.',
      validationStrategy: 'فلترة قراءة آمنة.',
    ),
    _def(
      name: 'periodic_services.create',
      aliases: const <String>['create_periodic_service'],
      description: 'إنشاء إعداد خدمة دورية لعقار بعد التحقق والتأكيد.',
      category: 'periodic_services',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['maintenance.update'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'property_query': _nullableString('اسم العقار أو الوحدة.'),
        'serviceType': _nullableEnum(
          <String>['cleaning', 'elevator', 'internet', 'water', 'electricity'],
          'نوع الخدمة.',
        ),
        'provider': _nullableString('مقدم الخدمة إن وجد.'),
        'cost': _nullableNumber('تكلفة الخدمة أو المبلغ الافتراضي.'),
        'billingMode': _nullableEnum(<String>['owner', 'separate', 'shared'], 'طريقة التحميل أو الفوترة.'),
        'sharedMethod': _nullableEnum(<String>['percent', 'fixed'], 'طريقة التوزيع للمياه/الكهرباء المشتركة.'),
        'meterNumber': _nullableString('رقم العداد للخدمة المنفصلة.'),
        'sharePercent': _nullableNumber('نسبة التحميل إن وجدت.'),
        'totalAmount': _nullableNumber('المبلغ الإجمالي إن وجد.'),
        'nextDueDate': _nullableString('تاريخ الاستحقاق القادم YYYY-MM-DD.'),
        'recurrenceMonths': _nullableNumber('تكرار الخدمة بالأشهر.'),
        'remindBeforeDays': _nullableNumber('التذكير قبل الموعد بالأيام.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'يحتاج المستخدم صلاحية إدارة الصيانة أو الخدمات.',
        'الخدمات المعقدة أو المشتركة قد تتطلب إكمالًا من شاشة الخدمات.',
        'لا يتم الإنشاء بدون تحديد العقار ونوع الخدمة والحقول المطلوبة.',
      ],
      handlerName: 'periodic_services.create',
      readBackTool: 'periodic_services.search',
      examplesAr: const <String>['أضف خدمة تنظيف شهرية لبرج النخيل'],
      disambiguationStrategy: 'إذا تعدد العقار اطلب الاختيار. إذا كانت المياه/الكهرباء المشتركة ناقصة فاطلب التفاصيل أو افتح الشاشة.',
      validationStrategy: 'تحقق من العقار ونوع الخدمة والجدولة قبل التأكيد.',
    ),
    _def(
      name: 'periodic_services.update',
      aliases: const <String>['update_periodic_service'],
      description: 'تحديث إعداد خدمة دورية موجودة بعد التحقق والتأكيد.',
      category: 'periodic_services',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.high,
      requiresConfirmation: true,
      requiredPermissions: const <String>['maintenance.update'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'property_query': _nullableString('اسم العقار أو الوحدة.'),
        'serviceType': _nullableEnum(
          <String>['cleaning', 'elevator', 'internet', 'water', 'electricity'],
          'نوع الخدمة.',
        ),
        'provider': _nullableString('مقدم الخدمة الجديد إن وجد.'),
        'cost': _nullableNumber('التكلفة الجديدة.'),
        'billingMode': _nullableEnum(<String>['owner', 'separate', 'shared'], 'طريقة التحميل أو الفوترة.'),
        'sharedMethod': _nullableEnum(<String>['percent', 'fixed'], 'طريقة التوزيع للمياه/الكهرباء المشتركة.'),
        'meterNumber': _nullableString('رقم العداد.'),
        'sharePercent': _nullableNumber('نسبة التحميل.'),
        'totalAmount': _nullableNumber('المبلغ الإجمالي.'),
        'nextDueDate': _nullableString('تاريخ الاستحقاق القادم YYYY-MM-DD.'),
        'recurrenceMonths': _nullableNumber('تكرار الخدمة بالأشهر.'),
        'remindBeforeDays': _nullableNumber('التذكير قبل الموعد بالأيام.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>[
        'يجب تحديد خدمة موجودة بدقة.',
        'الخدمات المشتركة المعقدة قد تتطلب إكمالًا من الشاشة.',
      ],
      handlerName: 'periodic_services.update',
      readBackTool: 'periodic_services.search',
      examplesAr: const <String>['عدّل موعد خدمة المصعد في برج النخيل'],
      disambiguationStrategy: 'إذا تعدد العقار اطلب الاختيار.',
      validationStrategy: 'لا تنفذ بدون تغيير فعلي أو تحديد دقيق.',
    ),
    _def(
      name: 'app.open_screen',
      aliases: const <String>[
        'navigate_to_screen',
        'open_tenant_entry',
        'open_property_entry',
        'open_contract_entry',
        'open_maintenance_entry',
        'open_contract_invoice_history',
      ],
      description: 'فتح شاشة داخل التطبيق عند الحاجة.',
      category: 'system',
      operationType: AiToolOperationType.system,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['app.navigate'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'screen': _nullableString('اسم الشاشة أو هدف الفتح.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا يفتح شاشة غير متاحة لهذا الحساب.', 'لا يعتبر فتح الشاشة تنفيذًا لعملية كتابة.'],
      handlerName: 'app.open_screen',
      readBackTool: null,
      examplesAr: const <String>['افتح شاشة إضافة عقد'],
      disambiguationStrategy: 'إذا كانت الشاشة غير واضحة اقترح أكثر الخيارات قربًا.',
      validationStrategy: 'يتحقق من المسار المسموح فقط.',
    ),
    _def(
      name: 'notifications.get',
      aliases: const <String>['get_notifications'],
      description: 'عرض تنبيهات النظام الحالية.',
      category: 'system',
      operationType: AiToolOperationType.read,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['app.help'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'kind': _nullableString('نوع التنبيه.'),
        'includeDismissed': _nullableBoolean('تضمين المقروءة.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['تعرض فقط تنبيهات النطاق الحالي.'],
      handlerName: 'notifications.get',
      readBackTool: null,
      examplesAr: const <String>['أرني التنبيهات الحالية'],
      disambiguationStrategy: 'لا ينطبق.',
      validationStrategy: 'فلاتر قراءة.',
    ),
    _def(
      name: 'notifications.open_target',
      aliases: const <String>['open_notification_target'],
      description: 'فتح العنصر المرتبط بالتنبيه.',
      category: 'system',
      operationType: AiToolOperationType.system,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['app.navigate'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'notificationRef': _nullableString('مرجع التنبيه.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['لا يفتح أهدافًا غير متاحة أو ناقصة.'],
      handlerName: 'notifications.open_target',
      readBackTool: null,
      examplesAr: const <String>['افتح هدف التنبيه الحالي'],
      disambiguationStrategy: 'لا ينطبق.',
      validationStrategy: 'يتحقق من مرجع التنبيه قبل الفتح.',
    ),
    _def(
      name: 'notifications.mark_read',
      aliases: const <String>['mark_notification_read'],
      description: 'تعليم تنبيه كمقروء.',
      category: 'system',
      operationType: AiToolOperationType.write,
      riskLevel: AiToolRiskLevel.low,
      requiresConfirmation: false,
      requiredPermissions: const <String>['app.help'],
      inputSchema: _schema(<String, Map<String, dynamic>>{
        'notificationRef': _nullableString('مرجع التنبيه.'),
      }),
      resultSchema: _simpleResultSchema(),
      businessRules: const <String>['يجب أن يكون مرجع التنبيه صالحًا وفي نطاق الحساب.'],
      handlerName: 'notifications.mark_read',
      readBackTool: 'notifications.get',
      examplesAr: const <String>['علّم هذا التنبيه كمقروء'],
      disambiguationStrategy: 'لا ينطبق.',
      validationStrategy: 'تحقق من المرجع قبل التنفيذ.',
    ),
  ];

  static List<AiToolDefinition> get catalog =>
      List<AiToolDefinition>.unmodifiable(_definitions);

  static AiToolDefinition? tryResolve(String toolName) {
    final normalized = fromOpenAiName(toolName).trim();
    for (final definition in _definitions) {
      if (definition.matches(normalized)) return definition;
    }
    return null;
  }

  static AiToolDefinition resolve(String toolName) {
    final definition = tryResolve(toolName);
    if (definition == null) {
      throw UnsupportedError('AI tool is not registered: $toolName');
    }
    return definition;
  }

  static String toOpenAiName(String canonicalName) {
    return canonicalName.replaceAll('.', '__');
  }

  static String fromOpenAiName(String openAiName) {
    final normalized = openAiName.trim();
    for (final definition in _definitions) {
      if (toOpenAiName(definition.name) == normalized) return definition.name;
      for (final alias in definition.aliases) {
        if (toOpenAiName(alias) == normalized || alias == normalized) {
          return definition.name;
        }
      }
    }
    return normalized.replaceAll('__', '.');
  }

  static List<Map<String, dynamic>> buildOpenAiTools({
    required bool isOfficeMode,
    required bool canWrite,
    required bool canReadAll,
    String? userMessage,
  }) {
    final filtered = _definitions.where((definition) {
      if (!definition.supported) return false;
      if (!canWrite && _isMutatingOperation(definition.operationType)) {
        return false;
      }
      if (!canReadAll && definition.requiredPermissions.contains('reports.financial')) {
        return definition.category != 'reports' || !isOfficeMode;
      }
      return true;
    });

    return filtered
        .map((definition) => _openAiTool(
              toOpenAiName(definition.name),
              '${definition.description} (canonical: ${definition.name})',
              definition.inputSchema,
            ))
        .map(_enforceStrictFunctionTool)
        .toList(growable: false);
  }

  static bool _isMutatingOperation(AiToolOperationType type) {
    return type == AiToolOperationType.write ||
        type == AiToolOperationType.deleteAction ||
        type == AiToolOperationType.export;
  }

  static Map<String, dynamic> _enforceStrictFunctionTool(
    Map<String, dynamic> tool,
  ) {
    final function =
        Map<String, dynamic>.from(tool['function'] as Map? ?? const <String, dynamic>{});
    final parameters =
        Map<String, dynamic>.from(function['parameters'] as Map? ?? const <String, dynamic>{});
    parameters['type'] = 'object';
    parameters['additionalProperties'] = false;
    final properties = Map<String, dynamic>.from(
      parameters['properties'] as Map? ?? const <String, dynamic>{},
    );
    final propertyNames = properties.keys.toList(growable: false);
    parameters['required'] = propertyNames;
    function['strict'] = true;
    function['parameters'] = parameters;
    return <String, dynamic>{
      'type': 'function',
      'function': function,
    };
  }

  static Map<String, dynamic> _openAiTool(
    String name,
    String description,
    Map<String, dynamic> inputSchema,
  ) {
    return <String, dynamic>{
      'type': 'function',
      'function': <String, dynamic>{
        'name': name,
        'description': description,
        'strict': true,
        'parameters': inputSchema,
      },
    };
  }

  static String _toolName(Map<String, dynamic> tool) {
    final function = tool['function'];
    if (function is! Map) return '';
    return (function['name'] ?? '').toString();
  }

  static AiToolDefinition _def({
    required String name,
    required List<String> aliases,
    required String description,
    required String category,
    required AiToolOperationType operationType,
    required AiToolRiskLevel riskLevel,
    required bool requiresConfirmation,
    required List<String> requiredPermissions,
    required Map<String, dynamic> inputSchema,
    required Map<String, dynamic>? resultSchema,
    required List<String> businessRules,
    required String handlerName,
    required String? readBackTool,
    required List<String> examplesAr,
    required String disambiguationStrategy,
    required String validationStrategy,
    bool supported = true,
  }) {
    return AiToolDefinition(
      name: name,
      aliases: aliases,
      description: description,
      category: category,
      operationType: operationType,
      riskLevel: riskLevel,
      requiresConfirmation: requiresConfirmation,
      requiredPermissions: requiredPermissions,
      inputSchema: inputSchema,
      resultSchema: resultSchema,
      businessRules: businessRules,
      handlerName: handlerName,
      readBackTool: readBackTool,
      examplesAr: examplesAr,
      disambiguationStrategy: disambiguationStrategy,
      validationStrategy: validationStrategy,
      supported: supported,
    );
  }

  static Map<String, dynamic> _schema(
    Map<String, Map<String, dynamic>> properties,
  ) {
    return <String, dynamic>{
      'type': 'object',
      'additionalProperties': false,
      'properties': properties,
      'required': properties.keys.toList(growable: false),
    };
  }

  static Map<String, dynamic> _nullableString(String description) {
    return <String, dynamic>{
      'type': <String>['string', 'null'],
      'description': description,
    };
  }

  static Map<String, dynamic> _nullableBoolean(String description) {
    return <String, dynamic>{
      'type': <String>['boolean', 'null'],
      'description': description,
    };
  }

  static Map<String, dynamic> _nullableNumber(String description) {
    return <String, dynamic>{
      'type': <String>['number', 'null'],
      'description': description,
    };
  }

  static Map<String, dynamic> _nullableEnum(
    List<String> values,
    String description,
  ) {
    return <String, dynamic>{
      'type': <String>['string', 'null'],
      'enum': <dynamic>[...values, null],
      'description': description,
    };
  }

  static Map<String, dynamic> _nullableArrayOfStrings(String description) {
    return <String, dynamic>{
      'type': <String>['array', 'null'],
      'description': description,
      'items': <String, dynamic>{
        'type': 'string',
      },
    };
  }

  static Map<String, dynamic> _simpleResultSchema() {
    return <String, dynamic>{
      'type': 'object',
      'additionalProperties': false,
      'properties': <String, dynamic>{
        'success': <String, dynamic>{'type': <String>['boolean', 'null']},
        'message': <String, dynamic>{'type': <String>['string', 'null']},
      },
      'required': const <String>['success', 'message'],
    };
  }

  static Map<String, dynamic> _reportSchema(String reportType) {
    return <String, dynamic>{
      'type': 'object',
      'additionalProperties': false,
      'properties': <String, dynamic>{
        'report_type': <String, dynamic>{
          'type': 'string',
          'enum': <String>[reportType],
        },
        'period': <String, dynamic>{'type': <String>['object', 'null']},
        'currency': <String, dynamic>{'type': <String>['string', 'null']},
        'filters': <String, dynamic>{'type': <String>['object', 'null']},
        'totals': <String, dynamic>{'type': <String>['object', 'null']},
        'rows': <String, dynamic>{'type': <String>['array', 'null']},
        'generated_at': <String, dynamic>{'type': <String>['string', 'null']},
      },
      'required': const <String>[
        'report_type',
        'period',
        'currency',
        'filters',
        'totals',
        'rows',
        'generated_at',
      ],
    };
  }
}
