workflows:
  ios-app-store:
    name: iOS App Store
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: darvoo_appstore

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - forsa_pro_appstore_profile_v3
        certificates:
          - ejarz_pro_distribution
      vars:
        BUNDLE_ID: com.forsapro.app

    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
        - $HOME/Library/Caches/CocoaPods

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Analyze Flutter project
        script: flutter analyze

      - name: Set up iOS code signing
        script: xcode-project use-profiles

      - name: Build signed iOS IPA
        script: flutter build ipa --release --build-name=1.0 --build-number=$BUILD_NUMBER

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: false
        submit_to_app_store: false
