name: aqdak
description: تطبيق عقدك لإدارة وتجهيز ومتابعة عقود الإيجار.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  pdf: 3.11.3
  cross_file: 0.3.5+4
  shared_preferences: ^2.5.3
  cloud_firestore: ^5.6.12
  cloud_functions: ^5.6.0
  file_picker: ^8.3.7
  flutter_webrtc: ^1.4.0
  flutter_secure_storage: ^10.3.4
  firebase_auth: ^5.7.0
  firebase_core: ^3.15.2
  firebase_messaging: ^15.2.10
  firebase_storage: ^12.4.10
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^17.2.4
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  webview_flutter: ^4.14.1
  webview_flutter_android: ^4.14.1
  webview_flutter_wkwebview: ^3.26.2
  package_info_plus: ^8.3.1
  firebase_app_check: 0.3.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/images/
  fonts:
    - family: IBM Plex Sans Arabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 800
    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai-Regular.ttf
          weight: 400
        - asset: assets/fonts/Dubai-Medium.ttf
          weight: 600
        - asset: assets/fonts/Dubai-Bold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 800
