// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBznylrbAURL9k4Cfg76-9vFAH26ll4yqk',
    appId: '1:142850470461:web:8bbc4f7a9c7f70ecb97054',
    messagingSenderId: '142850470461',
    projectId: 'darvoo',
    authDomain: 'darvoo.firebaseapp.com',
    storageBucket: 'darvoo.firebasestorage.app',
    measurementId: 'G-J83MPQY91W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8cMGGXNhk9kS11amer1kI0nqax8mrXy0',
    appId: '1:142850470461:android:713464ae047721fbb97054',
    messagingSenderId: '142850470461',
    projectId: 'darvoo',
    storageBucket: 'darvoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP36F_IZYChgjlWd3w_9klQwuOxZcRSrQ',
    appId: '1:142850470461:ios:5e9fa1d0ad211d60b97054',
    messagingSenderId: '142850470461',
    projectId: 'darvoo',
    storageBucket: 'darvoo.firebasestorage.app',
    iosBundleId: 'com.darvoo.owner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP36F_IZYChgjlWd3w_9klQwuOxZcRSrQ',
    appId: '1:142850470461:ios:3b6ef9dfa73837b6b97054',
    messagingSenderId: '142850470461',
    projectId: 'darvoo',
    storageBucket: 'darvoo.firebasestorage.app',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBznylrbAURL9k4Cfg76-9vFAH26ll4yqk',
    appId: '1:142850470461:web:87f73930fc491865b97054',
    messagingSenderId: '142850470461',
    projectId: 'darvoo',
    authDomain: 'darvoo.firebaseapp.com',
    storageBucket: 'darvoo.firebasestorage.app',
    measurementId: 'G-HL61J7DHTB',
  );
}